# Override Values for MATLAB Production Server Helm Chart

global:
  # MathWorks Cloud Reference Architecture License, example: "yes" (in quotes)
  agreeToLicense: ""
  # Network License Manager: server host and port number, example: 27000@hostname
  licenseServer: 27000@hostname
  # Override for private container registry, example: my-registry.example.com
  images:
    registry: ""
    pullSecret: ""

  # Ingress settings (optional)
  ingressController:
    enabled: false  # Create 'Ingress' API object
    name: nginx
    annotations:
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/load-balance: "round_robin"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "300"

    # Ingress host
    domainBase: matlabprodserver.mwcloudtest.com
    # Ingress https (tls termination)
    tls:
      enabled: false
      # Name of kubernetes.io/tls secret with certificate data
      secretName: ""

matlabProductionServerSettings:
  # CTF files are placed in this volume for automatic deployment.
  autoDeploy:
    # Enable RESTful API for management of CTF 'Deployable Archives'
    archivesApi:  #  Since R2025a
      enabled: false
      createPVC: false  #  Enable when archivesApi is enabled and dynamic
                        #  volume provisioning in enabled on K8s cluster.
      storageClassName: ""
      accessMode: ReadWriteOnce  #  ReadWriteMany when replicaCount > 1
      size: "4Gi"
    # _OR_
    # Inline mount options: hostpath, nfs, pvc, azurefileshare, empty (default)
    # Note: archives API is supported with pvc and empty volume types.
    volumeType: "empty"
    # Node mount dir, example: /mnt/share/autodeploy
    hostpath: ""
    # =================================================================
    # NFS server, example: server-sb08-nfs
    server: ""
    # NFS subpath, example: /vmgr/sandbox/share/autodeploy
    path: ""
    # =================================================================
    # Persistent-Volume-Claim name, example: autodeploy-pv-claim
    # If archives API is enabled, PVC Access-Mode should be RWO or RWX.
    claimName: ""
    # =================================================================
    # Azure storage account file share name, example: auto-deploy-share
    shareName: ""
    # Azure storage account key secret name, example: azure-file-secret
    secretName: ""
    # =================================================================

  # CTF Access Control (OAuth2)
  # https://www.mathworks.com/help/mps/server/access_control.html
  # -------------------------------------------------------------
  accessControl:  #  Since R2025a
    enabled: false
  # -------------------------------------------------------------
    identityProvider: |-
      {
        "version": "1.0.0",
        "jwtIssuer": "URL of the authorization server that issued the JWT",
        "appId": "String representing the application ID of the client",
        "jwksUri": "URL of the authorization server public keys",
        "jwksStrictSSL": false,
        "jwksTimeOut": 120,
        "userAttributeName": "email",
        "groupAttributeName": "groups"
      }
  # Note: FQDNs configured in 'jwtIssuer' and 'jwksUri' above
  #       MUST be reachable from within the K8s cluster network.
  # -------------------------------------------------------------
    policyRules: |-
      {
        "version": "1.0.0",
        "policy" : [
          {
            "id": "policy1",
            "description": "Access Control policy for MATLAB Production Server",
            "rule": [
              {
                "id": "rule1",
                "description": "Users that can execute/modify any deployable archive",
                "subject": { "users": ["user1@example.com", "user2@example.com"] },
                "resource": { "ctf": ["*"] },
                "action": ["execute", "modify"]
              },
              {
                "id": "rule2",
                "description": "Groups that can execute a specific deployable archive",
                "subject": { "groups": ["aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"] },
                "resource": { "ctf": ["myModel"] },
                "action": ["execute"]
              }
            ]
          }
        ]
      }
  # -------------------------------------------------------------

deploymentSettings:
  replicaCount: 1
  restartPolicy: Always

optionalSettings:
  Redis:
    # Redis service fully qualified name, example: redis.namespace.svc.cluster.local
    host: ""
    name: myRedis
    secretName: ""

  Prometheus:
    # Create a ServiceMonitor [monitoring.coreos.com/v1] for metrics discovery.
    # Requires Prometheus and Prometheus Operator (CRDs) to be pre-installed.
    enabled: false
    # Helm release name or app.kubernetes.io/part-of label of Prometheus stack.
    # ServiceMonitor needs to match on this value (if Prometheus is enabled).
    matchOn: prometheus
