apiVersion: v1
kind: ConfigMap
metadata:
  name: matlab-production-server-config
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
data:
  main_config: |
    --http 9910
    --ssl-verify-peer-mode no-verify-peer
    --ssl-protocols TLSv1.1,TLSv1.2
    --ssl-ciphers ALL
    --mcr-root /opt/matlabruntime/{{ .Values.images.matlabRuntime.variant }}
    --num-workers {{ .Values.matlabProductionServerSettings.numWorkers | default 1 }}
    --worker-restart-interval 12:00:00
    --worker-memory-check-interval 0:00:30
    --queue-time-trigger 0:00:00.25
    --queue-time-target 0:00:00.25
    --num-threads 1
    --auto-deploy-root ./auto_deploy
    --request-size-limit 64MB
    --log-severity information
    --log-rotation-size 100MB
    --log-archive-root ./old_logs
    --log-archive-max-size 1GB
    --log-root ./log
    --log-stdout
    --license {{ .Values.global.licenseServer | default "27000@hostname" }}
    --license-grace-period 2:30
    --license-poll-interval 0:10
    --pid-root ./pid
    --endpoint-root ./endpoint
    --extract-root .
    --socket-root ./.mps_socket
    --main-log-format text/plain
    --disable-control-c
    --enable-graceful-shutdown
    --no-display
    --enable-http-pipelining
    --server-memory-threshold 2GB
    --server-memory-threshold-overflow-action purge_responses
    --enable-discovery
    --enable-metrics

  {{- if .Values.optionalSettings.Redis.host }}
  mps_cache_config: |
    {"Connections":
        {"{{ .Values.optionalSettings.Redis.name }}": 
            {"Provider":"Redis",
            "Host":{{ .Values.optionalSettings.Redis.host | quote }},
            "Port":{{ .Values.optionalSettings.Redis.port | default 6379 }}}
        }
    }
  {{- end }}

