#
# Expose MATLAB Production Server internal endpoint
#
kind: Service
apiVersion: v1
metadata:
    name: matlab-production-server
    namespace: {{ .Release.Namespace }}
    labels:
        app: mps
        release: {{ .Release.Name }}
spec:
    selector:
        app: mps
    ports:
    - name: mps-port
      port: 9910
      targetPort: 9910
    type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: matlab-production-server-ingress
    namespace: {{ .Release.Namespace }}
    labels:
        release: {{ .Release.Name }}
    annotations:
        {{ if .Values.global.ingressController }}
        ## set ingress-conroller vendor-specific annotations:
        {{- range $key, $value := .Values.global.ingressController.annotations }}
        {{ $key }}: {{ quote $value }}
        {{- end }}
        {{ end }}
spec:
    ingressClassName: {{ .Values.global.ingressController.name }}
    rules:
      - host: {{ .Values.global.ingressController.domainBase }}
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                  service:
                      name: matlab-production-server
                      port:
                          number: 9910

